// skill_pdf.js - Fixed version
// Author: NI MBAYA
// Username: GuruTech
// Botname: XGURU
// Repository: https://github.com/ADDICT-HUB/XGURU
// Newsletter: 120363421164015033@newsletter

const { evt } = require("../gift");
const fs = require("fs-extra");
const path = require("path");
const config = require("../config");

let PDFDocument;
try {
    PDFDocument = require("pdfkit");
    console.log("✅ PDFKit module loaded");
} catch (error) {
    console.log("⚠️ PDFKit not available, using fallback mode");
    PDFDocument = null;
}

// Create a fallback PDF generator
function createSimplePDF(text, filename) {
    return new Promise((resolve, reject) => {
        try {
            if (!PDFDocument) {
                // Create a simple text file as fallback
                const content = `XGURU PDF Document\n\n` +
                               `Generated by XGURU Bot\n` +
                               `Author: NI MBAYA\n` +
                               `Username: GuruTech\n` +
                               `Repository: https://github.com/ADDICT-HUB/XGURU\n` +
                               `Newsletter: 120363421164015033@newsletter\n\n` +
                               `Content:\n${text}`;
                
                fs.writeFileSync(filename, content);
                resolve(filename);
                return;
            }
            
            const doc = new PDFDocument();
            const stream = fs.createWriteStream(filename);
            
            doc.pipe(stream);
            
            // Add header
            doc.fontSize(20)
               .text('XGURU PDF Document', { align: 'center' })
               .moveDown();
            
            doc.fontSize(12)
               .text('Generated by XGURU Bot', { align: 'center' })
               .text('Author: NI MBAYA', { align: 'center' })
               .text('Username: GuruTech', { align: 'center' })
               .text('Repository: https://github.com/ADDICT-HUB/XGURU', { align: 'center' })
               .text('Newsletter: 120363421164015033@newsletter', { align: 'center' })
               .moveDown(2);
            
            // Add content
            doc.fontSize(14)
               .text('Content:', { underline: true })
               .moveDown();
            
            doc.fontSize(12)
               .text(text);
            
            doc.end();
            
            stream.on('finish', () => {
                resolve(filename);
            });
            
            stream.on('error', reject);
            
        } catch (error) {
            reject(error);
        }
    });
}

evt({
    pattern: "topdf",
    fromMe: true,
    desc: "Convert text to PDF",
    type: "tools"
}, async (message, match) => {
    try {
        if (!match) {
            await message.reply("📝 Please provide text to convert to PDF\n" +
                              `Example: *${config.PREFIX}topdf Hello World*`);
            return;
        }
        
        await message.reply("⏳ Creating PDF document...");
        
        const filename = `xuru-pdf-${Date.now()}.pdf`;
        const filepath = path.join(__dirname, "..", "temp", filename);
        
        await fs.ensureDir(path.dirname(filepath));
        await createSimplePDF(match, filepath);
        
        await message.sendFile(filepath, {
            mimetype: "application/pdf",
            filename: `XGURU_Document_${Date.now()}.pdf`,
            caption: `📄 *PDF Document Created*\n\n` +
                    `🤖 Generated by XGURU Bot\n` +
                    `👤 Author: NI MBAYA\n` +
                    `👥 Username: GuruTech\n` +
                    `📦 Repository: https://github.com/ADDICT-HUB/XGURU\n` +
                    `📬 Newsletter: 120363421164015033@newsletter`
        });
        
        // Cleanup
        setTimeout(() => {
            fs.unlink(filepath).catch(() => {});
        }, 5000);
        
    } catch (error) {
        console.error("PDF creation error:", error);
        await message.reply(`❌ Failed to create PDF\n` +
                          `💡 Make sure PDFKit is installed:\n` +
                          `npm install pdfkit\n\n` +
                          `🤖 XGURU Bot - by NI MBAYA`);
    }
});

evt({
    pattern: "textfile",
    fromMe: true,
    desc: "Create a text file",
    type: "tools"
}, async (message, match) => {
    try {
        if (!match) {
            await message.reply("📝 Please provide text for the file\n" +
                              `Example: *${config.PREFIX}textfile Hello World*`);
            return;
        }
        
        await message.reply("⏳ Creating text file...");
        
        const filename = `xuru-text-${Date.now()}.txt`;
        const filepath = path.join(__dirname, "..", "temp", filename);
        
        await fs.ensureDir(path.dirname(filepath));
        
        const content = `XGURU Text Document\n\n` +
                       `Generated by XGURU Bot\n` +
                       `Author: NI MBAYA\n` +
                       `Username: GuruTech\n` +
                       `Repository: https://github.com/ADDICT-HUB/XGURU\n` +
                       `Newsletter: 120363421164015033@newsletter\n\n` +
                       `Content:\n${match}`;
        
        await fs.writeFile(filepath, content);
        
        await message.sendFile(filepath, {
            mimetype: "text/plain",
            filename: `XGURU_Text_${Date.now()}.txt`,
            caption: `📝 *Text File Created*\n\n` +
                    `🤖 Generated by XGURU Bot\n` +
                    `👤 Author: NI MBAYA\n` +
                    `📦 Repository: https://github.com/ADDICT-HUB/XGURU`
        });
        
        // Cleanup
        setTimeout(() => {
            fs.unlink(filepath).catch(() => {});
        }, 5000);
        
    } catch (error) {
        console.error("Text file creation error:", error);
        await message.reply("❌ Failed to create text file");
    }
});

evt({
    pattern: "doc",
    fromMe: true,
    desc: "Document tools help",
    type: "tools"
}, async (message) => {
    await message.reply(`📄 *XGURU Document Tools*\n\n` +
                       `🤖 *Bot:* XGURU by NI MBAYA\n` +
                       `👥 *Username:* GuruTech\n` +
                       `📦 *Repo:* https://github.com/ADDICT-HUB/XGURU\n\n` +
                       `🔧 *Available Commands:*\n` +
                       `• ${config.PREFIX}topdf <text> - Convert text to PDF\n` +
                       `• ${config.PREFIX}textfile <text> - Create text file\n\n` +
                       `💡 *Note:* PDFKit module ${PDFDocument ? '✓ Loaded' : '✗ Not installed'}\n` +
                       `Install with: npm install pdfkit`);
});

console.log("✅ PDF Tools plugin loaded - XGURU by NI MBAYA");
